// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmqMvZujB18QSOwx9QY0FT8cfYFo1hcHo',
    appId: '1:746253962893:web:3b0099e0cffc1ad1841cc4',
    messagingSenderId: '746253962893',
    projectId: 'mobile-app-d1f98',
    authDomain: 'mobile-app-d1f98.firebaseapp.com',
    storageBucket: 'mobile-app-d1f98.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhS5pIMC6Q2skutTDbUZJa9bOAVomAu5A',
    appId: '1:746253962893:android:e43722ae518c1fe3841cc4',
    messagingSenderId: '746253962893',
    projectId: 'mobile-app-d1f98',
    storageBucket: 'mobile-app-d1f98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVupeJIDqktgUyml7JJi8ybzAXmWezqYw',
    appId: '1:746253962893:ios:d06e542d920d2945841cc4',
    messagingSenderId: '746253962893',
    projectId: 'mobile-app-d1f98',
    storageBucket: 'mobile-app-d1f98.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp2',
  );
}
